### ISSUE TITLE
命令“set "targetDir=G:\项目代码

### ISSUE THREAD

**Issue by gywei** [magicodes/Magicodes.NET#10]
错误	1	命令“set "targetDir=G:\项目代码\Magicodes.NET.git\trunk\Magicodes.Web\Plus\Plugins\Magicodes.RouteDebugger"
if not exist %targetDir% md %targetDir%
echo f | xcopy "G:\项目代码\Magicodes.NET.git\trunk\Plus\Magicodes.RouteDebugger\bin\Debug\Magicodes.RouteDebugger.dll" %targetDir% /Y”已退出，代码为 255。	Magicodes.RouteDebugger

**Comment by magicodes** [comment]
目前项目工程目录路径不支持中文路径，因为批处理将中文路径视为特殊符号。
在项目工程的项目生成事件中写了大量批处理太自动推送到插件目录。要解决这个问题得重写整个批处理。目前建议使用英文路径。
