### ISSUE TITLE
未能加载文件或程序集“XXX”或它的某一个依赖项。系统找不到指定的文件

### ISSUE THREAD

**Issue by lpandnn** [magicodes/Magicodes.NET#11]
[FileNotFoundException: 未能加载文件或程序集“Microsoft.Owin.Security.QQ, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。]
   Magicodes.Strategy.Identity.AppAuthConfig.ConfigureAuth(IAppBuilder app) +0
   Magicodes.Strategy.Identity.Plus.GlobalConfigurationManager_OnConfiguration_AppBuilder(Object sender, EventArgs e) +74
   System.EventHandler.Invoke(Object sender, EventArgs e) +0
   Magicodes.Core.Web.GlobalConfigurationManager.AppBuilder(IAppBuilder app) in e:\李鹏\MVC模块化\Magicodes.NET-master\Magicodes.NET-master\Magicodes.Core.Web\GlobalConfigurationManager.cs:73
   Magicodes.Core.Web.Startup.Configuration(IAppBuilder app) in e:\李鹏\MVC模块化\Magicodes.NET-master\Magicodes.NET-master\Magicodes.Core.Web\Startup.cs:28

[TargetInvocationException: 调用的目标发生了异常。]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +92
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +21
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +118
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +254
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder) +89
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +856
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +136
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +159

**Comment by magicodes** [comment]
## 请不要使用中文目录路径
## 请重新全部编译启动再试

**Comment by mbydzyr** [comment]
编译整个解决方案就不会报这个异常了
