### ISSUE TITLE
web/theme/dafault 文件夹命名错误！

### ISSUE THREAD

**Issue by cxs198699** [magicodes/Magicodes.NET#13]
![untitled](https://cloud.githubusercontent.com/assets/7359020/5894602/cbfecbee-a544-11e4-8abc-a56a280edd1e.png)

**Comment by magicodes** [comment]
没看懂是什么意思

**Comment by magicodes** [comment]
好像这个目录是多余的，已移除。

**Comment by tjcccc** [comment]
> 好像这个目录是多余的，已移除。

不是多余的，是主题样式（和通用样式分开的）。

我目录名字手滑打错，应该是“default”（默认主题）。。

**Comment by tjcccc** [comment]
@cxs198699 感谢指正！
