### ISSUE TITLE
生成后执行的copy命令不能把依赖项拷贝到插件目录下，建议把输出路径修改到插件目录下

### ISSUE THREAD

**Issue by wudiliujie** [magicodes/Magicodes.NET#14]
生成后执行的copy命令不能把依赖项拷贝到插件目录下，建议把输出路径修改到插件目录下
还有怎么把留言弄成分类，比如FQA Question

**Comment by magicodes** [comment]
依赖项的复制是需要自己再修改XCopy命令的。
为了防止插件目录存放大量重复的依赖项以及无关的文件，不建议将输出路径修改为插件目录。
业务功能暂时并未继续拓展，目前在研究T4生成这块，如果T4基架基本完成，才会重新完善这些业务功能。
