### ISSUE TITLE
XCOPY问题

### ISSUE THREAD

**Issue by iguolee** [magicodes/Magicodes.NET#15]
错误	1	命令“set "targetDir=D:\Magicodes.NET\T4\Librarys" 
if not exist %targetDir% md %targetDir%
echo f | xcopy "D:\Magicodes.NET\Magicodes.Web.Interfaces\bin\Debug\Magicodes.Web.Interfaces.dll" %targetDir% /Y”已退出，代码为 255。	Magicodes.Web.Interfaces

目录里面没有中文，也报这个错误！

**Comment by magicodes** [comment]
你之前是不是调试过？T4模板调试，如果是的话，会占用dll，导致无法复制成功。
另外，应该有更详细的错误日志的，希望你能够提供。
