### ISSUE TITLE
在首页点击进入登录页面后，输入用户名密码登录出错

### ISSUE THREAD

**Issue by hxling** [magicodes/Magicodes.NET#18]
![qq 20150324101507](https://cloud.githubusercontent.com/assets/3139817/6794701/023fcf1c-d210-11e4-9e0e-e3d79aece9ac.jpg)

**Comment by magicodes** [comment]
是否重新编译了所有的代码？

**Comment by magicodes** [comment]
重新生成解决方案。

**Comment by lovemory** [comment]
http://localhost:4780/admin/Account/Register   找不到视图。

magicodes  你有测试过注册页面吗？
