### ISSUE TITLE
后台点击退出，页面不存在

### ISSUE THREAD

**Issue by jetablezhu** [magicodes/Magicodes.NET#21]
**在后台界面，点击退出按钮，找不到相应的文件，是路由错误或还没完成该功能吧**
![错误截图](http://i3.tietuku.com/a8cb99b2ef3dbef8.png)
![错误截图](http://i3.tietuku.com/4a3a7e22867c0972.png)

**Comment by magicodes** [comment]
哦。多谢反馈。我回去看看。

**Comment by magicodes** [comment]
已解决。
