### ISSUE TITLE
插件中的数据库迁移CMS及Blog

### ISSUE THREAD

**Issue by feilang864** [magicodes/Magicodes.NET#22]
Magicodes.CMS和Magicodes.Blogs都有插件，但是也都有数据库，如何用codefirst更新数据库

**Comment by jetablezhu** [comment]
**只要正常访问cms、blog的页面，就会创建**

**Comment by magicodes** [comment]
对的。多谢各位支持。不过CMS和Blog目前只是增加了数据模型，在我有空的前提下，我会去完善的。
