### ISSUE TITLE
PDF插件不知道怎么用

### ISSUE THREAD

**Issue by jetablezhu** [magicodes/Magicodes.NET#27]
**Magicodes.PDFViewer插件路由、参数、js，不知道哪里的问题，用不起来，希望能给个说明**
![截图](http://i3.tietuku.com/a191e76ad8bd55fd.png)

**Comment by magicodes** [comment]
好的。这些问题我都记下了，只是最近一直加班。

**Comment by magicodes** [comment]
已更新文档。代码已签入。
