### ISSUE TITLE
运行出现的错误

### ISSUE THREAD

**Issue by FlynnLong** [magicodes/Magicodes.NET#32]
![default](https://cloud.githubusercontent.com/assets/11752774/6956012/98e314fa-d919-11e4-9f83-dd94c44e8c28.png)

**Comment by FlynnLong** [comment]
运行的时候出现的错误，

**Comment by jetablezhu** [comment]
检查web项目中的数据库连接字符串配置

**Comment by FlynnLong** [comment]
非常感谢！


发自我的 iPhone

**Comment by magicodes** [comment]
已添加"初始化插件菜单失败，请检查数据库连接字符串是否正确！"异常提示，后续会签入。
