### ISSUE TITLE
没有与 PrimitiveType“DateTimeOffset”的概念端类型“DateTimeOffset”对应的存储类型。

### ISSUE THREAD

**Issue by tiantianhaohaowen** [magicodes/Magicodes.NET#4]
1.运行环境是cpu 64位，vs2012
2.debug编译通过
3.F5 调试，在Magicodes.Core.ApplicationContext 文件中添加插件模块
  #region 添加插件菜单  if (r.GetQueryable().Any(p => p.PlusId == plusInfo.Id))提示该错误：
没有与 PrimitiveType“DateTimeOffset”的概念端类型“DateTimeOffset”对应的存储类型。

**Comment by magicodes** [comment]
你的数据库是什么版本？
另外再试试重新全部编译呢？

**Comment by tiantianhaohaowen** [comment]
我的数据库是sql server 2005

**Comment by magicodes** [comment]
sql Server 2005不支持这个类型（datetimeoffset ），具体你可以查看以下链接：http://msdn.microsoft.com/zh-cn/library/bb630289.aspx
如果不方面升级Sql Server，你可以使用SQl Express。

datetimeoffset 用于定义一个与采用 24 小时制并可识别时区的一日内时间相组合的日期。
适用范围：SQL Server（SQL Server 2008 至当前版本），Windows Azure SQL Database（初始版本至当前版本）。

**Comment by tiantianhaohaowen** [comment]
1.在 Magicodes.Web 的web.config 的connectionString中添加了数据库的uid.和password
 <add name="Magicodes.NET" connectionString="Data Source=.;Initial Catalog=Magicodes.Models.Mvc;Integrated Security=True;uid=sa;password=sa;" providerName="System.Data.SqlClient"  />
    <add name="magicodes_blog" connectionString="Data Source=.;Initial Catalog=Magicodes.NET_Blogs;Integrated Security=True;uid=sa;password=sa;" providerName="System.Data.SqlClient" />
    <add name="magicodes_cms" connectionString="Data Source=.;Initial Catalog=Magicodes.NET_CMS;Integrated Security=True;uid=sa;password=sa;" providerName="System.Data.SqlClient" />
2.发生的错误还是如上，数据库的表也没有创建

**Comment by magicodes** [comment]
看来你还是没看懂。。。也就是SQL 2008以下版本不支持此数据类型，你需要使用 SQl 2008或以上版本才能够使用。VS自带的sql Express应该是2008版本的，你可以使用Express实例试试。

**Comment by jjcl521** [comment]
admin 登陆密码多少？

**Comment by tiantianhaohaowen** [comment]
我已经安装了sqlserver2008 64位的。现在系统上有双sqlserver.还是同样的问题

**Comment by magicodes** [comment]
你检查下数据库实例是否配置正确。双数据肯定是两个实例。

**Comment by tiantianhaohaowen** [comment]
我把系统中关于DateTimeOffset 类型全部转换成 DateTime类型。结果在  #region 添加插件菜单
            var r = APIContext<string>.Current.SiteAdminNavigationRepository;
            if (r == null) return;
            foreach (var plusInfo in PlusManager.PluginsList)
            {
                if (plusInfo.PlusConfigInfo != null && plusInfo.PlusConfigInfo.PlusMenus != null && plusInfo.PlusConfigInfo.PlusMenus.Length > 0)
                {
                    if (r.GetQueryable().Any(p => p.PlusId == plusInfo.Id)) ------》该处还是报提示DateTimeOffset的错误
                    {

**Comment by magicodes** [comment]
在Magicodes.Web.Interfaces下还有DateTimeOffset类型的定义，是一个基类。

**Comment by magicodes** [comment]
建议你用sql Express 或者 SQL 2008或以上。之所以支持只DateTimeOffset类型是因为OData的日期类型只支持该格式，后续可能会考虑兼容吧，目前尚无精力重构此块。
