### ISSUE TITLE
CMS缺少配置文件

### ISSUE THREAD

**Issue by jjcl521** [magicodes/Magicodes.NET#8]
路径Magicodes.NET\Magicodes.NET\Plus\CMS\Magicodes.CMS\App_Data\Config
缺少NLog.config

**Comment by magicodes** [comment]
你的启动项目错了，你应该启动Magicodes.Web。注意我标注的目录顺序，1.Web

**Comment by jjcl521** [comment]
那我知道了，我以为每个项目都可以单独运行呢
