### ISSUE TITLE
迁移数据时碰到的问题。

### ISSUE THREAD

**Issue by yuanbeier** [magicodes/Magicodes.NET#9]
根据文档执行命令。有错误，提示：在程序集“Magicodes.Web”中未找到迁移配置类型。(在 Visual Studio 中，您可从程序包管理器控制台使用 Enable-Migrations 命令添加迁移配置)。

**Comment by magicodes** [comment]
你需要选择模型程序集，比如Magicodes.Models.Mvc。
另外，你执行迁移数据的命令的原因是？你添加数据实体了？

**Comment by yuanbeier** [comment]
没有用过数据迁移，也太了解。我想根据实体生成一份本地数据库。我以为用数据迁移可以完成。

**Comment by magicodes** [comment]
数据迁移不是这么用的。
你如果启动了项目，项目会根据Web.config中的数据库连接来生成一个数据库。所以确保有建库权限。

**Comment by yuanbeier** [comment]
在Magiccodes.Web的Web.config文件中没看到配置数据库的地方。请问在哪里找到？

**Comment by magicodes** [comment]
有的呀。。。，如： 
 <connectionStrings>
    
    <add name="Magicodes.NET" connectionString="Data Source=.;Initial Catalog=Magicodes.Models.Mvc;Integrated Security=True" providerName="System.Data.SqlClient" />
    <add name="magicodes_blog" connectionString="Data Source=.;Initial Catalog=Magicodes.NET_Blogs;Integrated Security=True" providerName="System.Data.SqlClient" />
    <add name="magicodes_cms" connectionString="Data Source=.;Initial Catalog=Magicodes.NET_CMS;Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>

**Comment by yuanbeier** [comment]
谢谢，看到了，我MSSQL服务没启动。
